/*
MySQL Data Transfer
Source Host: 65.75.244.120
Source Database: woody
Target Host: 65.75.244.120
Target Database: woody
Date: 18-11-2008 15:19:09
*/

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `store_catalogue_sales`;
-- ----------------------------
-- Table structure for store_catalogue_sales
-- ----------------------------
CREATE TABLE `store_catalogue_sales` (
  `salecode` varchar(100) collate latin1_general_ci NOT NULL,
  `pageid` int(10) NOT NULL,
  `orderid` int(10) NOT NULL,
  `price` int(5) NOT NULL,
  `item_definitionid` int(10) NOT NULL,
  `item_specialspriteid` int(5) NOT NULL,
  `package_name` varchar(200) collate latin1_general_ci default NULL,
  `package_description` varchar(200) collate latin1_general_ci default NULL,
  `ispackage` enum('true','false') collate latin1_general_ci NOT NULL default 'false',
  PRIMARY KEY  (`salecode`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `store_catalogue_sales` VALUES ('floor', '3', '1', '2', '2407', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('CF_50_goldbar', '4', '5', '50', '1765', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('CF_20_moneybag', '4', '4', '20', '1764', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('CF_10_coin_gold', '4', '3', '10', '1762', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('CF_5_coin_silver', '4', '2', '5', '1766', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('CF_1_coin_bronze', '4', '1', '1', '1763', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('CFC_200_moneybag', '4', '6', '200', '2157', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('CFC_500_goldbar', '4', '7', '500', '2156', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_red_5', '5', '1', '25', '0', '0', 'Red Roller 5Pack', '5 Red Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_red_3', '5', '2', '15', '0', '0', 'Red Roller 3Pack', '3 Red Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('roller_red', '5', '3', '7', '1448', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_blue_5', '5', '4', '25', '0', '0', 'Blue Roller 5Pack', '5 Blue Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_blue_3', '5', '5', '15', '0', '0', 'Blue Roller 3Pack', '3 Blue Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('roller_blue', '5', '6', '7', '1442', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_green_5', '5', '7', '25', '0', '0', 'Green Roller 5Pack', '5 Green Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_green_3', '5', '8', '15', '0', '0', 'Green Roller 3Pack', '3 Green Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('roller_green', '5', '9', '7', '1444', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_navy_5', '5', '10', '25', '0', '0', 'Navy Roller 5Pack', '5 Navy Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_navy_3', '5', '11', '15', '0', '0', 'Navy Roller 3Pack', '3 Navy Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('roller_navy', '5', '12', '7', '1445', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_purple_5', '5', '14', '25', '0', '0', 'Purple Roller 5Pack', '5 Purple Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('roller_purple', '5', '16', '7', '1447', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('deal_rollers_purple_3', '5', '15', '15', '0', '0', 'Purple Roller 3Pack', '3 Purple Rollers in a convenient pack', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('tele_london', '6', '1', '5', '1179', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('tele_portaloo', '6', '2', '4', '1181', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('tele_wardrobe', '6', '3', '3', '1180', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('pet0', '7', '1', '20', '1320', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('pet1', '7', '2', '20', '1320', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('pet2', '7', '3', '20', '1320', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('deal_dogfood', '8', '1', '2', '0', '0', 'Doggy Bones', 'Natural nutrition for the barking one', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('deal_catfood', '8', '2', '2', '0', '0', 'Sardines', 'Fresh catch of the day', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('deal_crocfood', '8', '3', '2', '0', '0', 'T-Bones', 'For the croc!', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('deal_cabbage', '8', '4', '2', '0', '0', 'Cabbage', 'Health food for pets', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('dogfood', '8', '5', '1', '1321', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('catfood', '8', '6', '1', '1322', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('crocfood', '8', '7', '1', '1827', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('cabbage', '8', '8', '1', '1323', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('waterbowlblue', '8', '9', '2', '1324', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('waterbowlbrown', '8', '10', '2', '1325', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('waterbowlgreen', '8', '11', '2', '1326', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('waterbowlred', '8', '12', '2', '1327', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('waterbowlyellow', '8', '13', '2', '1328', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('chocmouse', '8', '14', '1', '1337', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('marzipanman', '8', '15', '1', '1334', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('petball1', '8', '16', '2', '1329', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('petball2', '8', '17', '2', '1330', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('petball3', '8', '18', '2', '1331', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('petball4', '8', '19', '2', '1332', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('petball5', '8', '20', '2', '1333', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bed_silo_two', '9', '1', '3', '1030', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bed_silo_one', '9', '2', '3', '1029', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('shelves_silo', '9', '3', '3', '1003', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('sofa_silo', '9', '4', '3', '1013', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('sofachair_silo', '9', '5', '3', '1021', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('kuttafel', '9', '6', '1', '1031', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('silo_gate', '9', '7', '6', '1227', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('silo_screen', '9', '8', '3', '1225', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('silo_corner', '9', '9', '3', '1223', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('chair_silo', '9', '10', '3', '1012', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('safe_silo', '9', '11', '3', '1681', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('barchair_silo', '9', '12', '3', '1465', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('table_silo_med', '9', '13', '3', '1007', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gothicchair', '10', '1', '10', '1789', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gothicsofa', '10', '2', '7', '1790', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gothicstool', '10', '3', '5', '1791', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gothic_carpet1', '10', '4', '5', '1829', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gothic_carpet2', '10', '5', '5', '1830', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('goth_table', '10', '6', '15', '1772', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gothrailing', '10', '7', '8', '1771', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gothgate', '10', '8', '10', '1769', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('goth_torch', '10', '9', '7', '2373', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('goth_fountain', '10', '10', '7', '2370', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gothiccandle', '10', '11', '8', '1770', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('industrialfan', '10', '12', '5', '2372', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('deal_soundmachine1', '11', '1', '10', '0', '0', 'Soundmachine starterset', 'Gray soundmachine with Duck Funk sampleset', 'true');
INSERT INTO `store_catalogue_sales` VALUES ('soundset1', '11', '2', '3', '1858', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soundset2', '11', '3', '3', '1860', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soundset4', '11', '5', '3', '1860', '0', '', '', 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soundset5', '11', '6', '3', '1860', '0', '', '', 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soundset3', '11', '4', '3', '1860', '0', '', '', 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soundset6', '11', '7', '3', '1863', '0', '', '', 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soundset7', '11', '8', '3', '1864', '0', '', '', 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soundset9', '11', '10', '3', '1865', '0', '', '', 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soundset8', '11', '9', '3', '1865', '0', '', '', 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candy_bar', '12', '1', '3', '1618', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candy_corner', '12', '2', '3', '1626', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candy_hatch', '12', '3', '6', '1634', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candy_sofachair', '12', '4', '3', '1136', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candy_sofa', '12', '5', '4', '1139', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candy_rug', '12', '6', '0', '1128', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candy_bed_one', '12', '7', '3', '1137', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candy_bed_two', '12', '8', '4', '1138', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wall_china', '13', '1', '8', '1707', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('corner_china', '13', '2', '8', '1708', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('shelve_china', '13', '3', '8', '1688', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('chair_china', '13', '4', '5', '1675', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('table_china', '13', '5', '6', '1676', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('sofa_china', '13', '6', '9', '1454', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('poster_china', '13', '7', '3', '2409', '57', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('knots_china', '13', '8', '5', '2409', '58', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('lantern_china', '13', '9', '9', '1453', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('chair_norja', '14', '1', '3', '1015', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('couch_norja', '14', '2', '3', '1014', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('table_norja_med', '14', '3', '3', '2410', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('shelves_norja', '14', '4', '3', '1001', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soft_sofachair_norja', '14', '5', '3', '1174', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soft_sofa_norja', '14', '6', '4', '1175', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('norja_bardesk', '14', '7', '3', '1224', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('norja_barcorner', '14', '8', '3', '1222', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('norja_hatch', '14', '9', '6', '1226', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('norja_shutter', '14', '10', '5', '1706', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('norja_shutter_corner', '14', '11', '4', '1705', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bed_armas_two', '15', '1', '3', '1032', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bed_armas_one', '15', '2', '3', '1042', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('fireplace_armas', '15', '3', '4', '1040', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bartable_armas', '15', '4', '3', '1117', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('table_armas', '15', '5', '3', '1037', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bench_armas', '15', '6', '3', '1036', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('divider_armas', '15', '7', '3', '1220', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('corner_armas', '15', '8', '3', '1219', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('gate_armas', '15', '9', '6', '1221', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('shelves_armas', '15', '10', '3', '1035', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bar_armas', '15', '11', '4', '1116', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bar_chair_armas', '15', '12', '1', '1118', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('lamp_armas', '15', '13', '3', '1041', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('candle_armas', '15', '14', '3', '1177', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('small_table_armas', '15', '15', '2', '1038', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('small_chair_armas', '15', '16', '1', '1039', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bed_budgetb_one', '17', '1', '3', '1140', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bed_budgetb_two', '17', '2', '3', '1141', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('shelves_basic', '17', '3', '3', '1173', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bar_basic', '17', '4', '4', '1172', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('fridge', '17', '5', '6', '1178', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('lamp_basic', '17', '6', '3', '1176', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bed_polyfon_two', '18', '1', '4', '1025', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bed_polyfon_one', '18', '2', '3', '1026', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('fireplace_polyfon', '18', '3', '5', '1046', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('sofa_polyfon', '18', '4', '4', '1020', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('sofachair_polyfon', '18', '5', '3', '1019', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bar_polyfon', '18', '6', '5', '1110', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('mode_bardesk', '18', '7', '3', '1113', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('mode_barcorner', '18', '8', '3', '1114', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('mode_hatch', '18', '9', '6', '1218', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('dinerchair_polyfon', '18', '10', '3', '1005', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('dinertable_polyfon', '18', '12', '4', '1135', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('coffeetable_polyfon2', '18', '13', '3', '1016', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('table_polyfon_small', '18', '14', '1', '1004', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('shelves_polyfon', '18', '15', '4', '1002', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('polyfon_zshelf', '18', '16', '1', '1011', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('tv_luxus', '19', '1', '6', '1155', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wood_tv', '19', '2', '4', '1127', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('red_tv', '19', '3', '3', '1126', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('stickies', '19', '4', '3', '2360', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('pizzabox', '19', '5', '3', '1105', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('drinks', '19', '6', '3', '1106', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bottle', '19', '7', '3', '1112', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('holodice', '19', '8', '6', '1213', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('cakewasalie', '19', '9', '4', '1207', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('menorah', '19', '10', '3', '1187', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bunny', '19', '11', '3', '1210', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('mummy', '19', '12', '3', '2490', '44', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wcandleset', '19', '13', '3', '1198', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('rcandleset', '19', '14', '3', '1199', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('ham', '19', '15', '3', '1189', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('alert', '19', '16', '5', '1295', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bath', '20', '1', '6', '1156', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('sink', '20', '2', '3', '1157', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('duck', '20', '3', '1', '1159', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('toilet_blue', '20', '4', '4', '1158', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('toilet_red', '20', '5', '4', '1161', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('toilet_yellow', '20', '6', '4', '1162', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('tile_blue', '20', '7', '3', '1160', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('tile_red', '20', '8', '3', '1163', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('tile_yellow', '20', '9', '3', '1164', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_flowers', '21', '1', '4', '1206', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_rose', '21', '2', '3', '1154', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_sunflower', '21', '3', '3', '1153', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_yukka', '21', '4', '3', '1147', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_ananas', '21', '5', '3', '1142', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_bonsai', '21', '6', '3', '1145', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_big_cactus', '21', '7', '3', '1146', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_small_cactus', '21', '8', '1', '1144', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_fruittree', '21', '9', '3', '1143', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_bulrush', '21', '10', '3', '1826', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_aloevera', '21', '11', '6', '1111', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_mazehedge', '21', '12', '5', '1825', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('plant_mazegate', '21', '13', '6', '1824', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('imptele', '2', '1', '25', '1296', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('hockeystick1', '22', '1', '3', '2409', '52', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('hockeystick2', '22', '2', '3', '2409', '53', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('hockeystick3', '22', '3', '3', '2409', '54', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('scoreboard', '22', '4', '6', '1294', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bballthrophy', '22', '5', '6', '1246', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bballhoop', '22', '6', '3', '2409', '51', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('bballcourt', '22', '7', '3', '1244', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('sportbench', '22', '8', '6', '1245', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_straight_tartan', '22', '9', '3', '1455', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_straight_asphalt', '22', '12', '3', '1457', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_straight_grass', '22', '15', '3', '1456', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_corner_tartan', '22', '10', '3', '1458', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_corner_asphalt', '22', '13', '3', '1459', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_corner_grass', '22', '16', '3', '1460', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_goal_tartan', '22', '11', '3', '1461', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_goal_asphalt', '22', '14', '3', '1462', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('track_goal_grass', '22', '17', '3', '1463', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('soccerlamp', '22', '18', '4', '1464', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard4', '23', '1', '3', '1073', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard5', '23', '2', '3', '1077', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard', '23', '3', '3', '1043', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standardb', '23', '4', '3', '1152', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standarda', '23', '5', '3', '1151', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard3', '23', '6', '3', '1066', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard2', '23', '7', '3', '1060', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard8', '23', '8', '3', '1149', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard7', '23', '9', '3', '1148', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard1', '23', '10', '3', '1052', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard6', '23', '11', '3', '1103', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_standard9', '23', '12', '3', '1150', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_soft', '23', '13', '3', '1119', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_soft1', '23', '14', '3', '1120', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_soft2', '23', '15', '3', '1121', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_soft3', '23', '16', '3', '1122', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_soft4', '23', '17', '3', '1123', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_soft5', '23', '18', '3', '1124', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_soft6', '23', '19', '3', '1125', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('doormat_love', '23', '20', '1', '1017', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('doormat0', '23', '21', '1', '1018', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('doormat1', '23', '22', '1', '1053', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('doormat2', '23', '23', '1', '2412', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('doormat3', '23', '24', '1', '2413', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('doormat4', '23', '25', '1', '2411', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('doormat5', '23', '26', '1', '2414', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('doormat6', '23', '27', '1', '1075', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_handwoven', '23', '28', '3', '1044', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('carpet_polarbear', '23', '29', '4', '1045', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_duck_bronze', '26', '1', '8', '1297', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_globe_bronze', '26', '2', '8', '1298', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_fish_bronze', '26', '3', '8', '1299', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_duo_bronze', '26', '4', '8', '1300', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_champion_bronze', '26', '5', '8', '1301', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_classic_bronze', '26', '6', '8', '1314', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_duck_silver', '26', '7', '10', '1309', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_globe_silver', '26', '8', '10', '1310', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_fish_silver', '26', '9', '10', '1311', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_duo_silver', '26', '10', '10', '1312', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_champion_silver', '26', '11', '10', '1313', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_classic_silver', '26', '12', '10', '1308', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_duck_gold', '26', '13', '12', '1303', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_globe_gold', '26', '14', '12', '1304', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_fish_gold', '26', '15', '12', '1305', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_duo_gold', '26', '16', '12', '1306', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_champion_gold', '26', '17', '12', '1301', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('trophy_classic_gold', '26', '18', '12', '1307', '0', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper1', '3', '2', '2', '2408', '1', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper2', '3', '3', '2', '2408', '2', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper3', '3', '4', '2', '2408', '3', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper4', '3', '5', '2', '2408', '4', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper5', '3', '6', '2', '2408', '5', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper6', '3', '7', '2', '2408', '6', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper7', '3', '8', '2', '2408', '7', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper8', '3', '9', '2', '2408', '8', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper9', '3', '10', '2', '2408', '9', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper10', '3', '11', '2', '2408', '10', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper11', '3', '12', '3', '2408', '11', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper12', '3', '13', '3', '2408', '12', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper13', '3', '14', '3', '2408', '13', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper14', '3', '15', '3', '2408', '14', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper15', '3', '16', '3', '2408', '15', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper16', '3', '17', '3', '2408', '16', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper17', '3', '18', '3', '2408', '17', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper18', '3', '19', '3', '2408', '18', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper19', '3', '20', '3', '2408', '19', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper20', '3', '21', '3', '2408', '20', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper21', '3', '22', '3', '2408', '21', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper22', '3', '23', '3', '2408', '22', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper23', '3', '24', '3', '2408', '23', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper24', '3', '25', '3', '2408', '24', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper25', '3', '26', '3', '2408', '25', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper26', '3', '27', '3', '2408', '26', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper27', '3', '28', '3', '2408', '27', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper28', '3', '29', '3', '2408', '28', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper29', '3', '30', '3', '2408', '29', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper30', '3', '31', '3', '2408', '30', null, null, 'false');
INSERT INTO `store_catalogue_sales` VALUES ('wallpaper31', '3', '32', '3', '2408', '31', null, null, 'false');
